Default:
    Active: True
    Language: en_US.UTF-8
    Keyboard: us
    PackageArgs:
    SaveRepos:  True
    Timezone: America/New_York
    RootPass: meego
    DefaultUser: meego
    DefaultUserPass: meego
    PartSize: 1900
    PostScripts:
        - rpm
    Groups:
        - MeeGo Core
        - Minimal MeeGo X Window System

CORE:
    PartSize: 1000
    BootloaderAppend: "quiet"
    BootloaderTimeout: 0
    PostScripts:
        - cleanup
NETBOOK:
    PartSize: 1900
    BootloaderAppend: "quiet"
    BootloaderTimeout: 0
    PostScripts:
        - cleanup
        - flash
    Groups:
        - X for Netbooks
        - Virtual Machine Support
        - Printing
        - Games
    Kernel: kernel-netbook
    PostScripts:
        - prelink
    ExtraPackages:
        - gdb
        - flash-plugin
        - adobe-release
    Architecture: ia32
    
Configurations:
    -   Name: MeeGo Core
        Active: True
        Baseline: "1.0.80"
        Platform: CORE
        FileName: core-ia32-testing
        Kernel: kernel-netbook
        Architecture: ia32
        Repos:
            - meego-core-testing
    -   Name: MeeGo Core N900
        Active: True
        Baseline: "1.0.80"
        Platform: CORE
        FileName: core-armv7l-n900-testing
        Kernel: kernel-n900
        Desktop:
        Architecture: armv7l
        Repos:
            - meego-core-testing
    -   Name: MeeGo Netbook/Nettop
        PartSize: 2900
        Active: True
        Baseline: "1.0.80"
        Platform: NETBOOK
        Desktop: meego
        FileName: netbook-ia32-testing
        Groups:
            - MeeGo Netbook Desktop
        Repos:
            - meego-core-testing
            - meego-netbook-testing
            - adobe
    -   Name: MeeGo Core
        Active: True
        Baseline: "1.0.80"
        Platform: CORE
        FileName: core-ia32
        Kernel: kernel-netbook
        Architecture: ia32
        Repos:
            - meego-core-daily
    -   Name: MeeGo Core N900
        Active: True
        Baseline: "1.0.80"
        Platform: CORE
        FileName: core-armv7l-n900
        Kernel: kernel-n900
        Desktop:
        Architecture: armv7l
        Repos:
            - meego-core-daily
    -   Name: MeeGo Netbook/Nettop
        PartSize: 2900
        Active: True
        Baseline: "1.0.80"
        Platform: NETBOOK
        Desktop: meego
        FileName: netbook-ia32-default
        Groups:
            - MeeGo Netbook Desktop
        Repos:
            - meego-core-daily
            - meego-netbook-daily
            - adobe
    -   Name: MeeGo Core 1.0 
        Active: True
        Baseline: "1.0"
        Platform: CORE
        FileName: core-ia32
        Kernel: kernel-netbook
        Architecture: ia32
        Repos:
            - meego-core-1.0
    -   Name: MeeGo Core 1.0 N900
        Active: True
        Baseline: "1.0"
        Platform: CORE
        FileName: core-armv7l-n900
        Kernel: kernel-n900
        Desktop:
        Architecture: armv7l
        Repos:
            - meego-core-1.0
    -   Name: MeeGo Netbook/Nettop 1.0 
        Active: True
        Baseline: "1.0"
        Platform: NETBOOK
        Desktop: meego
        FileName: netbook-ia32-default
        Groups:
            - MeeGo Netbook Desktop
        Repos:
            - meego-core-1.0
            - meego-netbook-1.0
            - meego-extra-1.0
            - adobe
