Default:
    Active: True
    Language: en_US.UTF-8
    Keyboard: us
    PackageArgs:
    SaveRepos:  True
    Timezone: America/New_York
    RootPass: meego
    DefaultUser: meego
    DefaultUserPass: meego
    PartSize: 1900
    PostScripts:
        - rpm
    Groups:
        - MeeGo Core
        - MeeGo Compliance

CORE:
    PartSize: 1000
    BootloaderAppend: "quiet"
    BootloaderTimeout: 0
    PostScripts:
        - cleanup
    Groups:
        - MeeGo X Window System
    NoChrootScripts:
        - buildname
NETBOOK:
    PartSize: 1900
    BootloaderAppend: "quiet"
    BootloaderTimeout: 0
    PostScripts:
        - cleanup
    Groups:
        - X for Netbooks
        - Virtual Machine Support
        - Printing
        - Games
        - MeeGo Netbook Desktop
    Kernel: kernel
    PostScripts:
        - prelink
        - cleanup
    NoChrootScripts:
        - buildname
    Architecture: ia32
    
Configurations:
    -   Name: MeeGo Core
        Active: True
        Baseline: "1.1.80"
        Platform: CORE
        FileName: core-ia32-testing
        Kernel: kernel-netbook
        Architecture: ia32
        Repos:
            - core-testing
    -   Name: MeeGo Core N900
        Active: True
        Baseline: "1.1.80"
        Platform: CORE
        FileName: core-armv7l-n900-testing
        Kernel: kernel-n900
        Desktop:
        Architecture: armv7l
        Repos:
            - core-testing
    -   Name: MeeGo Netbook/Nettop
        PartSize: 3000
        Active: True
        Baseline: "1.1.80"
        Platform: NETBOOK
        Desktop: meego
        FileName: netbook-ia32
        Groups:
            - MeeGo Netbook Desktop
            - Base Double Byte IME Support
            - MeeGo Base Development
        Repos:
            - core
            - netbook
        ExtraPackages:
            - chromium
    -   Name: MeeGo Core
        Active: True
        Baseline: "1.1.80"
        Platform: CORE
        FileName: core-ia32
        Kernel: kernel
        Architecture: ia32
        Repos:
            - core
    -   Name: MeeGo Core N900
        Active: True
        Baseline: "1.1.80"
        Platform: CORE
        FileName: core-armv7l-n900
        Kernel: kernel-adaptation-n900
        Desktop:
        Architecture: armv7l
        Repos:
            - core
